### ISSUE TITLE
[BUG] - MySQL doesn’t treat null as a valid default for NOT NULL fields

### ISSUE THREAD

**Issue by cybereyes-sunny** [go-co-op/gocron-gorm-lock#35]
### Describe the bug

Update Worker and Status Fields in CronJobLock to Use Compatible Default Values

### To Reproduce

follow the example and exec:

db.AutoMigrate(&gormlock.CronJobLock{})

### Version

github.com/go-co-op/gocron-gorm-lock v1.0.0

### Expected behavior

The Worker and Status fields in the CronJobLock struct currently have gorm:"not null;default:null". Setting null as a default for NOT NULL fields leads to migration errors in MySQL because MySQL doesn’t support null as a default for NOT NULL columns.

To make this compatible with MySQL and similar databases, these fields should be updated to use an empty string ('') as the default. This will allow migrations to run smoothly without encountering Invalid default value errors.

### Additional context

2024/10/28 09:29:11 failed to migrate database: Error 1067 (42000): Invalid default value for 'worker'

https://github.com/go-co-op/gocron-gorm-lock/blob/1a90c837c948be783ca949c88aa785c37e05d9c3/job_lock_struct.go#L18

https://github.com/go-co-op/gocron-gorm-lock/blob/1a90c837c948be783ca949c88aa785c37e05d9c3/job_lock_struct.go#L19

**Comment by manuelarte** [comment]
@cybereyes-sunny I created a PR, once it's merged the issue should be solved

**Comment by cybereyes-sunny** [comment]
Thanks for your work!

**Comment by manuelarte** [comment]
Version v1.0.1 with the fix has been released: https://github.com/go-co-op/gocron-gorm-lock/releases/tag/v1.0.1
